# Generated by Django 4.1.4 on 2023-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registroresiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idrr', models.CharField(max_length=13)),
                ('idr', models.CharField(max_length=13)),
                ('rut', models.CharField(max_length=13)),
                ('kilos', models.CharField(max_length=13)),
                ('fecha', models.CharField(max_length=13)),
                ('puntosobtenidos', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Residuos',
            fields=[
                ('idr', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=13)),
                ('puntaje', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=15)),
            ],
        ),
    ]
