# Generated by Django 4.1.4 on 2023-05-31 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miweb1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroresiduos',
            name='rut',
        ),
        migrations.AddField(
            model_name='registroresiduos',
            name='usuario',
            field=models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='miweb1.usuarios'),
        ),
        migrations.AlterField(
            model_name='registroresiduos',
            name='idr',
            field=models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='miweb1.residuos'),
        ),
    ]
