# Generated by Django 4.1.4 on 2023-05-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb1', '0002_remove_registroresiduos_rut_registroresiduos_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
