# Generated by Django 4.1.4 on 2023-06-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb1', '0003_rename_contraseña_usuarios_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroresiduos',
            name='idrr',
        ),
    ]
