# Generated by Django 4.1.4 on 2023-06-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb1', '0004_remove_registroresiduos_idrr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroresiduos',
            old_name='idr',
            new_name='idr_id',
        ),
    ]
