# Generated by Django 4.1.4 on 2023-06-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb1', '0005_rename_idr_registroresiduos_idr_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroresiduos',
            old_name='idr_id',
            new_name='idr',
        ),
    ]
